export enum Entities {
  Appointment = 'appointment',
  Admin = 'admin',
  Blog = 'blog',
  User = 'user',
  CalcLog = 'calc_log',
  Message = 'message',
  NextVisit = 'next_visit',
  Invoice = 'invoice',
  InvoiceDesc = 'invoice_desc',
  Car = 'car',
  CarExam = 'car_exam',
  CarReception = 'car_reception',
  JobTicket = 'job_ticket',
  JobConclusion = 'job_conclusion',
  WorkOrder = 'work_order',
  Warranty = 'warranty',
  WarrantyConditions = 'warranty_conditions',
  Image = 'image',
  Expense = 'expense',
  NotificationSubscriber = 'notification_subscriber',
}
